# Generated by Django 4.0.3 on 2022-05-04 14:37

import obapi.modelfields
from django.db import migrations

from obpages.utils import to_slug


def save_user_models(apps, schema_editor):
    model = apps.get_model("obpages", "user")
    db_alias = schema_editor.connection.alias
    for obj in model.objects.using(db_alias).all():
        obj.slug = to_slug(obj.username, max_length=150)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("obpages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=150, unique=False
            ),
            preserve_default=False,
        ),
        migrations.RunPython(save_user_models, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                editable=False, max_length=150, unique=True
            ),
        ),
    ]
