# Generated by Django 4.0.3 on 2022-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obpages", "0002_user_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("update_search_index", "Can update the search index"),
                    ("rebuild_search_index", "Can rebuild the search index"),
                ),
                "managed": False,
                "default_permissions": (),
                "verbose_name_plural": "Search Indexes",
            },
        ),
    ]
